spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeju_log_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root        # ? ?? MySQL ??? (?? root)
    password: rhkrwlgns        # ? ?? MySQL ????? ??? ??!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update    # ?? ?? ? ??? ?? ??
    show-sql: true        # ???? SQL ????

  # ?? ??? ?? ???? (20MB)
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB